### ISSUE TITLE
How do I make a team?

### ISSUE THREAD

**Issue by TechPro424** [Havhingstor/BetterTeamChat#1]
How do I make a team so send messages to?

**Comment by Havhingstor** [comment]
Sorry to reply just now.
BetterTeamChat uses the Vanille Minecraft teams, see for example https://minecraft.fandom.com/wiki/Commands/team for more information

**Comment by TechPro424** [comment]
But team is an op command
So an op needs to add you to a team for this mod to have a purpose?

**Comment by Havhingstor** [comment]
Yes, it is meant to be used in conjunction with the Minecraft teams.

**Comment by TechPro424** [comment]
Thank you for the clarification :)
